### ISSUE TITLE
Approve a pull request in a different repository

### ISSUE THREAD

**Issue by TravisEz13** [juliangruber/approve-pull-request-action#18]
Approve a pull request in a different repository

**Comment by juliangruber** [comment]
That would be great to have indeed :) Do you want to work on a pull request, should be 2/3 lines or something?

**Comment by TravisEz13** [comment]
Can you add a LICENSE.txt with the MIT license and I'll open a PR?

**Comment by juliangruber** [comment]
here you go: https://github.com/juliangruber/approve-pull-request-action/blob/master/LICENSE
