### ISSUE TITLE
Cross repository approve

### ISSUE THREAD

**Issue by theilgaard** [juliangruber/approve-pull-request-action#22]
Is it possible to trigger an approve on another repository provided the PAT has proper permissions?

I see there is no `repository` parameter.

**Comment by juliangruber** [comment]
Not yet, but that isn't hard to add. Check out https://github.com/juliangruber/merge-pull-request-action/pull/15/files, where this was done an a similar action. PRs welcome 🙌

**Comment by theilgaard** [comment]
Oh, you actually accepted a PR with exactly this feature :)

This was released in 1.1.0: https://github.com/juliangruber/approve-pull-request-action/releases/tag/v1.1.0

It is undocumented on the Actions Marketplace.

**Comment by juliangruber** [comment]
Oops :D

I updated the docs, thanks. I wished the action.yml would be displayed automatically

**Comment by theilgaard** [comment]
Thanks :) And thanks for the github action!
