### ISSUE TITLE
feature request: only approve once

### ISSUE THREAD

**Issue by zeke** [juliangruber/approve-pull-request-action#7]
Hey @juliangruber! 🎸

I have a workflow that runs on a schedule, opens a PR, and approves it. If the workflow runs a second time before the PR has merged, it will be approved a second (and third, and fourth...) time by this Action. This is not a huge problem, but it would be nifty if this Action could first check for the existence of an approving review before approving another time.

<img width="573" alt="Screen Shot 2020-09-24 at 12 48 52 PM" src="https://user-images.githubusercontent.com/2289/94192902-6dc47e00-fe64-11ea-86da-3a0ce424453e.png">

**Comment by zeke** [comment]
Hahaha

<img width="552" alt="Screen Shot 2020-09-24 at 8 01 24 PM" src="https://user-images.githubusercontent.com/2289/94221847-c7e33480-fea0-11ea-9ca9-240ea5b01fbd.png">

**Comment by juliangruber** [comment]
This makes a lot of sense!

**Comment by msasikanth** [comment]
If this is still an open issue, you should be able to add an if condition to this job in your GH Action to check what the review status is and prevent it from running when it's approved. You can check the status using this `github.event.review.state != approved`

**Comment by juliangruber** [comment]
Thanks so much @msasikanth, this should solve it :)
