### ISSUE TITLE
v2.0.5 can't create a github client

### ISSUE THREAD

**Issue by mscharley** [juliangruber/approve-pull-request-action#71]
Looks like there's some bad code in the big update PR (#70)

<img width="536" alt="image" src="https://github.com/juliangruber/approve-pull-request-action/assets/336509/43562fa7-6cfc-4cfe-b536-62b22da5f451">

**Comment by juliangruber** [comment]
Strange: https://github.com/juliangruber/approve-pull-request-action/commit/cd7907fb286b81b50661e9eed55d8b22d23c5bdf passed, but from the next commit on it didn't any more

**Comment by juliangruber** [comment]
We need to add the build step to CI
